CREATE TABLE [dbo].[Users]
(
    [Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [UserName] NVARCHAR(16) NOT NULL,
    [FirstName] NVARCHAR(58) NOT NULL,
    [LastName] NVARCHAR(58) NOT NULL,
    [Password] NVARCHAR(16) NOT NULL
)
